# TCL File Generated by Component Editor 7.2sp1 on:
# Wed Jun 11 15:31:25 EEST 2008
# DO NOT MODIFY

set_source_file "SRAM_16Bit_512K.v"
set_module "SRAM_16Bit_512K"
set_module_description ""
set_module_property "className" "sram_16bit_512k"
set_module_property "displayName" "SRAM_16Bit_512K"
set_module_property "group" "Terasic Technologies Inc"
set_module_property "instantiateInSystemModule" "true"
set_module_property "simulationFiles" "hdl/SRAM_16Bit_512K.v"
set_module_property "synthesisFiles" "SRAM_16Bit_512K.v"
set_module_property "version" "1.0.1"

# Module parameters

# Interface clk
add_interface "clk" "clock" "sink" "asynchronous"
# Ports in interface clk
add_port_to_interface "clk" "iCLK" "clk"

# Interface avalon_slave_0_export
add_interface "avalon_slave_0_export" "conduit" "end" "asynchronous"
# Ports in interface avalon_slave_0_export
add_port_to_interface "avalon_slave_0_export" "SRAM_DQ" "export"
add_port_to_interface "avalon_slave_0_export" "SRAM_ADDR" "export"
add_port_to_interface "avalon_slave_0_export" "SRAM_UB_N" "export"
add_port_to_interface "avalon_slave_0_export" "SRAM_LB_N" "export"
add_port_to_interface "avalon_slave_0_export" "SRAM_WE_N" "export"
add_port_to_interface "avalon_slave_0_export" "SRAM_CE_N" "export"
add_port_to_interface "avalon_slave_0_export" "SRAM_OE_N" "export"

# Interface avalon_slave_0
add_interface "avalon_slave_0" "avalon" "slave" "clk"
set_interface_property "avalon_slave_0" "isNonVolatileStorage" "false"
set_interface_property "avalon_slave_0" "burstOnBurstBoundariesOnly" "false"
set_interface_property "avalon_slave_0" "readLatency" "0"
set_interface_property "avalon_slave_0" "readWaitStates" "20"
set_interface_property "avalon_slave_0" "holdTime" "20"
set_interface_property "avalon_slave_0" "printableDevice" "false"
set_interface_property "avalon_slave_0" "readWaitTime" "20"
set_interface_property "avalon_slave_0" "setupTime" "20"
set_interface_property "avalon_slave_0" "addressAlignment" "DYNAMIC"
set_interface_property "avalon_slave_0" "writeWaitTime" "20"
set_interface_property "avalon_slave_0" "timingUnits" "Nanoseconds"
set_interface_property "avalon_slave_0" "minimumUninterruptedRunLength" "1"
set_interface_property "avalon_slave_0" "isMemoryDevice" "true"
set_interface_property "avalon_slave_0" "linewrapBursts" "false"
set_interface_property "avalon_slave_0" "writeWaitStates" "20"
set_interface_property "avalon_slave_0" "maximumPendingReadTransactions" "0"
# Ports in interface avalon_slave_0
add_port_to_interface "avalon_slave_0" "iDATA" "writedata"
add_port_to_interface "avalon_slave_0" "oDATA" "readdata"
add_port_to_interface "avalon_slave_0" "iADDR" "address"
add_port_to_interface "avalon_slave_0" "iWE_N" "write_n"
add_port_to_interface "avalon_slave_0" "iOE_N" "read_n"
add_port_to_interface "avalon_slave_0" "iCE_N" "chipselect_n"
add_port_to_interface "avalon_slave_0" "iBE_N" "byteenable_n"
