###########################################################################
#
# Generated by : Version 7.0 Build 33 02/05/2007 SJ Web Edition
#
# Project      : jop_vp
# Revision     : jop_vp
#
# Date         : Fri Apr 06 1:53:19 PM Central Europe Standard Time 2007
#
###########################################################################
 
 
# WARNING: Expected CUT_OFF_PATHS_BETWEEN_CLOCK_DOMAINS to be set to 'OFF', but it is set to 'ON'
#          In SDC, all clocks are related by default
# WARNING: Expected ENABLE_CLOCK_LATENCY to be set to 'ON', but it is set to 'OFF'
#          In SDC, create_generated_clock auto-generates clock latency
# WARNING: Expected DEFAULT_HOLD_MULTICYCLE to be set to 'ONE', but it is set to 'SAME AS MULTICYCLE'
#          In SDC, the Default Hold Multicycle is zero - equivalent to one in the Classic Timing Analyzer
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -use_tan_name
#
# ------------------------------------------


# Original Clock Setting Name: extclk
create_clock -period "20 MHz" \
             -name {ext_clk_i} {ext_clk_i}
# ---------------------------------------------
